kind: pipeline
type: docker
name: default
steps:
  - name: archlinux
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm make gcc pkgconf rustup
      - rustup update nightly
      - rustup default nightly
  - name: format-archlinux
    commands:
      - make fmt
    depends_on:
      - archlinux
  - name: test-archlinux
    commands:
      - make test
    depends_on:
      - format-archlinux
  - name: doc-archlinux
    commands:
      - make doc
    depends_on:
      - format-archlinux
  - name: install-archlinux
    commands:
      - make install
    depends_on:
      - test-archlinux
      - doc-archlinux
