kind: pipeline
type: docker
name: default
steps:
  - name: archlinux
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.arch64
  - name: ubuntu64
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.ubuntu64
