kind: pipeline
type: docker
name: default
steps:
  - name: make on archlinux
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm make gcc pkgconf rustup
      - rustup update nightly
      - rustup default nightly
      - make fmt
      - make test
      - make doc
      - make install
